spring:
  application:
    name: esercizio26092024
  jpa:
    hibernate:
      dialect: jakarta.persistence.jdbc.url
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
extra:
  jwt:
    expiration:
      minutes: 10
logging:
  level:
    root: INFO
    com.donato.esercizio.esercizio26092024.service.BookService: INFO
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html